INFO 2022-05-23 15:05:08 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 15:05:08 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 15:05:08 Started reloader process [32190] using statreload
INFO 2022-05-23 15:05:08 Started server process [32192]
INFO 2022-05-23 15:05:08 Waiting for application startup.
INFO 2022-05-23 15:05:08 Application startup complete.
WARNING 2022-05-23 15:13:13 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:13:13 Shutting down
INFO 2022-05-23 15:13:13 Waiting for application shutdown.
INFO 2022-05-23 15:13:13 Application shutdown complete.
INFO 2022-05-23 15:13:13 Finished server process [32192]
INFO 2022-05-23 15:13:14 Started server process [32333]
INFO 2022-05-23 15:13:14 Waiting for application startup.
INFO 2022-05-23 15:13:14 Application startup complete.
WARNING 2022-05-23 15:14:24 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 15:14:24 Shutting down
INFO 2022-05-23 15:14:24 Waiting for application shutdown.
INFO 2022-05-23 15:14:24 Application shutdown complete.
INFO 2022-05-23 15:14:24 Finished server process [32333]
WARNING 2022-05-23 15:18:39 StatReload detected file change in 'core/logger.py'. Reloading...
WARNING 2022-05-23 15:20:35 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:20:36 Started server process [32510]
INFO 2022-05-23 15:20:36 Waiting for application startup.
INFO 2022-05-23 15:20:36 Application startup complete.
ERROR 2022-05-23 15:20:52 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/exceptions.py", line 20, in http_exception_handle
    logger.error(exec)
AttributeError: 'Logger' object has no attribute 'error'
WARNING 2022-05-23 15:22:19 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:22:19 Shutting down
INFO 2022-05-23 15:22:20 Waiting for application shutdown.
INFO 2022-05-23 15:22:20 Application shutdown complete.
INFO 2022-05-23 15:22:20 Finished server process [32510]
INFO 2022-05-23 15:22:20 Started server process [32574]
INFO 2022-05-23 15:22:20 Waiting for application startup.
INFO 2022-05-23 15:22:20 Application startup complete.
WARNING 2022-05-23 15:35:13 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:35:13 Shutting down
INFO 2022-05-23 15:35:13 Waiting for application shutdown.
INFO 2022-05-23 15:35:13 Application shutdown complete.
INFO 2022-05-23 15:35:13 Finished server process [32574]
INFO 2022-05-23 15:35:14 Started server process [32883]
INFO 2022-05-23 15:35:14 Waiting for application startup.
INFO 2022-05-23 15:35:14 Application startup complete.
WARNING 2022-05-23 15:43:15 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:43:15 Shutting down
INFO 2022-05-23 15:43:15 Waiting for application shutdown.
INFO 2022-05-23 15:43:15 Application shutdown complete.
INFO 2022-05-23 15:43:15 Finished server process [32883]
WARNING 2022-05-23 15:43:35 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:43:39 Stopping reloader process [32190]
INFO 2022-05-23 15:46:46 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 15:46:46 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 15:46:46 Started reloader process [33219] using statreload
INFO 2022-05-23 15:46:47 Started server process [33221]
INFO 2022-05-23 15:46:47 Waiting for application startup.
INFO 2022-05-23 15:46:47 Application startup complete.
WARNING 2022-05-23 15:48:54 StatReload detected file change in 'core/logger.py'. Reloading...
INFO 2022-05-23 15:48:54 Shutting down
INFO 2022-05-23 15:48:54 Waiting for application shutdown.
INFO 2022-05-23 15:48:54 Application shutdown complete.
INFO 2022-05-23 15:48:54 Finished server process [33221]
INFO 2022-05-23 15:48:55 Started server process [33275]
INFO 2022-05-23 15:48:55 Waiting for application startup.
INFO 2022-05-23 15:48:55 Application startup complete.
ERROR 2022-05-23 15:49:02 1 validation error for Request
body -> status
  value is not a valid integer (type=type_error.integer)
INFO 2022-05-23 15:51:02 Shutting down
INFO 2022-05-23 15:51:03 Waiting for application shutdown.
INFO 2022-05-23 15:51:03 Application shutdown complete.
INFO 2022-05-23 15:51:03 Finished server process [33275]
INFO 2022-05-23 15:51:03 Stopping reloader process [33219]
INFO 2022-05-23 15:51:04 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 15:51:04 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 15:51:04 Started reloader process [33338] using statreload
INFO 2022-05-23 15:51:04 Started server process [33340]
INFO 2022-05-23 15:51:04 Waiting for application startup.
INFO 2022-05-23 15:51:04 Application startup complete.
ERROR 2022-05-23 15:51:06 1 validation error for Request
body -> status
  value is not a valid integer (type=type_error.integer)
INFO 2022-05-23 15:55:25 Shutting down
INFO 2022-05-23 15:55:25 Waiting for application shutdown.
INFO 2022-05-23 15:55:25 Application shutdown complete.
INFO 2022-05-23 15:55:25 Finished server process [33340]
INFO 2022-05-23 15:55:25 Stopping reloader process [33338]
INFO 2022-05-23 15:55:26 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 15:55:26 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 15:55:26 Started reloader process [33459] using statreload
INFO 2022-05-23 15:55:27 Started server process [33461]
INFO 2022-05-23 15:55:27 Waiting for application startup.
INFO 2022-05-23 15:55:27 Application startup complete.
ERROR 2022-05-23 15:55:32 1 validation error for Request
body -> status
  value is not a valid integer (type=type_error.integer)
WARNING 2022-05-23 15:56:13 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 15:56:13 Shutting down
INFO 2022-05-23 15:56:13 Waiting for application shutdown.
INFO 2022-05-23 15:56:13 Application shutdown complete.
INFO 2022-05-23 15:56:13 Finished server process [33461]
INFO 2022-05-23 15:56:14 Started server process [33492]
INFO 2022-05-23 15:56:14 Waiting for application startup.
INFO 2022-05-23 15:56:14 Application startup complete.
WARNING 2022-05-23 15:56:24 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 15:56:24 Shutting down
INFO 2022-05-23 15:56:24 Waiting for application shutdown.
INFO 2022-05-23 15:56:24 Application shutdown complete.
INFO 2022-05-23 15:56:24 Finished server process [33492]
INFO 2022-05-23 15:56:25 Started server process [33507]
INFO 2022-05-23 15:56:25 Waiting for application startup.
INFO 2022-05-23 15:56:25 Application startup complete.
ERROR 2022-05-23 15:56:28 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/exceptions.py", line 20, in http_exception_handle
    a = 1/0
ZeroDivisionError: division by zero
INFO 2022-05-23 15:57:19 Shutting down
INFO 2022-05-23 15:57:19 Waiting for application shutdown.
INFO 2022-05-23 15:57:19 Application shutdown complete.
INFO 2022-05-23 15:57:19 Finished server process [33507]
INFO 2022-05-23 15:57:19 Stopping reloader process [33459]
INFO 2022-05-23 15:57:20 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 15:57:20 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 15:57:20 Started reloader process [33535] using statreload
INFO 2022-05-23 15:57:21 Started server process [33537]
INFO 2022-05-23 15:57:21 Waiting for application startup.
INFO 2022-05-23 15:57:21 Application startup complete.
ERROR 2022-05-23 15:57:23 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/exceptions.py", line 20, in http_exception_handle
    a = 1/0
ZeroDivisionError: division by zero
WARNING 2022-05-23 15:58:43 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 15:58:43 Shutting down
INFO 2022-05-23 15:58:43 Waiting for application shutdown.
INFO 2022-05-23 15:58:43 Application shutdown complete.
INFO 2022-05-23 15:58:43 Finished server process [33537]
INFO 2022-05-23 15:58:44 Started server process [33554]
INFO 2022-05-23 15:58:44 Waiting for application startup.
INFO 2022-05-23 15:58:44 Application startup complete.
WARNING 2022-05-23 16:11:37 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:11:37 Shutting down
INFO 2022-05-23 16:11:37 Waiting for application shutdown.
INFO 2022-05-23 16:11:37 Application shutdown complete.
INFO 2022-05-23 16:11:37 Finished server process [33554]
INFO 2022-05-23 16:11:38 Started server process [33956]
INFO 2022-05-23 16:11:38 Waiting for application startup.
INFO 2022-05-23 16:11:38 Application startup complete.
INFO 2022-05-23 16:11:43 <starlette.requests.Request object at 0x11cc460a0>
WARNING 2022-05-23 16:17:04 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:17:04 Shutting down
INFO 2022-05-23 16:17:04 Waiting for application shutdown.
INFO 2022-05-23 16:17:04 Application shutdown complete.
INFO 2022-05-23 16:17:04 Finished server process [33956]
INFO 2022-05-23 16:17:05 Started server process [34058]
INFO 2022-05-23 16:17:05 Waiting for application startup.
INFO 2022-05-23 16:17:05 Application startup complete.
INFO 2022-05-23 16:17:05 <coroutine object Request.json at 0x13a46dc40>
WARNING 2022-05-23 16:17:55 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:17:55 Shutting down
INFO 2022-05-23 16:17:55 Waiting for application shutdown.
INFO 2022-05-23 16:17:55 Application shutdown complete.
INFO 2022-05-23 16:17:55 Finished server process [34058]
INFO 2022-05-23 16:17:56 Started server process [34088]
INFO 2022-05-23 16:17:56 Waiting for application startup.
INFO 2022-05-23 16:17:56 Application startup complete.
WARNING 2022-05-23 16:19:14 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:19:14 Shutting down
INFO 2022-05-23 16:19:14 Waiting for connections to close. (CTRL+C to force quit)
INFO 2022-05-23 16:19:24 Finished server process [34088]
ERROR 2022-05-23 16:19:24 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 112, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/requests.py", line 231, in body
    async for chunk in self.stream():
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/requests.py", line 216, in stream
    message = await self._receive()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 496, in receive
    await self.message_event.wait()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError
ERROR 2022-05-23 16:19:24 Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 627, in lifespan
    await receive()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

INFO 2022-05-23 16:19:25 Started server process [34135]
INFO 2022-05-23 16:19:25 Waiting for application startup.
INFO 2022-05-23 16:19:25 Application startup complete.
INFO 2022-05-23 16:19:37 <starlette.requests.Request object at 0x12776e850>
INFO 2022-05-23 16:20:49 <starlette.requests.Request object at 0x1277c5070>
INFO 2022-05-23 16:23:12 <starlette.requests.Request object at 0x1277c1820>
INFO 2022-05-23 16:23:52 <starlette.requests.Request object at 0x1277e5dc0>
INFO 2022-05-23 16:24:13 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 16:24:13 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 16:24:13 Started reloader process [34282] using statreload
INFO 2022-05-23 16:24:13 Started server process [34284]
INFO 2022-05-23 16:24:13 Waiting for application startup.
INFO 2022-05-23 16:24:13 Application startup complete.
INFO 2022-05-23 16:24:16 [ErrorWrapper(exc=ValidationError(model='ConfigSettingCreate', errors=[{'loc': ('status',), 'msg': 'value is not a valid integer', 'type': 'type_error.integer'}]), loc=('body',))]
WARNING 2022-05-23 16:25:34 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:25:34 Shutting down
INFO 2022-05-23 16:25:34 Waiting for application shutdown.
INFO 2022-05-23 16:25:34 Application shutdown complete.
INFO 2022-05-23 16:25:34 Finished server process [34284]
INFO 2022-05-23 16:25:35 Started server process [34319]
INFO 2022-05-23 16:25:35 Waiting for application startup.
INFO 2022-05-23 16:25:35 Application startup complete.
INFO 2022-05-23 16:25:40 [ErrorWrapper(exc=ValidationError(model='ConfigSettingCreate', errors=[{'loc': ('status',), 'msg': 'value is not a valid integer', 'type': 'type_error.integer'}]), loc=('body',))]
ERROR 2022-05-23 16:25:40 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/exceptions.py", line 24, in http_exception_handle
    data=exec.raw_errors.errors)
AttributeError: 'list' object has no attribute 'errors'
WARNING 2022-05-23 16:28:03 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:28:03 Shutting down
INFO 2022-05-23 16:28:03 Waiting for application shutdown.
INFO 2022-05-23 16:28:03 Application shutdown complete.
INFO 2022-05-23 16:28:03 Finished server process [34319]
INFO 2022-05-23 16:28:04 Started server process [34379]
INFO 2022-05-23 16:28:04 Waiting for application startup.
INFO 2022-05-23 16:28:04 Application startup complete.
INFO 2022-05-23 16:28:10 [ErrorWrapper(exc=ValidationError(model='ConfigSettingCreate', errors=[{'loc': ('status',), 'msg': 'value is not a valid integer', 'type': 'type_error.integer'}]), loc=('body',))]
ERROR 2022-05-23 16:28:10 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/exceptions.py", line 24, in http_exception_handle
    data=exec.raw_errors[0].errors)
AttributeError: 'ErrorWrapper' object has no attribute 'errors'
WARNING 2022-05-23 16:30:26 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:30:26 Shutting down
INFO 2022-05-23 16:30:26 Waiting for application shutdown.
INFO 2022-05-23 16:30:26 Application shutdown complete.
INFO 2022-05-23 16:30:26 Finished server process [34379]
INFO 2022-05-23 16:30:27 Started server process [34421]
INFO 2022-05-23 16:30:27 Waiting for application startup.
INFO 2022-05-23 16:30:27 Application startup complete.
INFO 2022-05-23 16:30:28 [ErrorWrapper(exc=ValidationError(model='ConfigSettingCreate', errors=[{'loc': ('status',), 'msg': 'value is not a valid integer', 'type': 'type_error.integer'}]), loc=('body',))]
ERROR 2022-05-23 16:30:28 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 95, in __call__
    response = await handler(request, exc)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/exceptions.py", line 23, in http_exception_handle
    return respErrorJson(error=err, status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, language="",
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 30, in respErrorJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
WARNING 2022-05-23 16:31:16 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:31:16 Shutting down
INFO 2022-05-23 16:31:16 Waiting for application shutdown.
INFO 2022-05-23 16:31:16 Application shutdown complete.
INFO 2022-05-23 16:31:16 Finished server process [34421]
INFO 2022-05-23 16:31:17 Started server process [34452]
INFO 2022-05-23 16:31:17 Waiting for application startup.
INFO 2022-05-23 16:31:17 Application startup complete.
INFO 2022-05-23 16:31:23 [ErrorWrapper(exc=ValidationError(model='ConfigSettingCreate', errors=[{'loc': ('status',), 'msg': 'value is not a valid integer', 'type': 'type_error.integer'}]), loc=('body',))]
WARNING 2022-05-23 16:32:56 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:32:56 Shutting down
INFO 2022-05-23 16:32:56 Waiting for application shutdown.
INFO 2022-05-23 16:32:56 Application shutdown complete.
INFO 2022-05-23 16:32:56 Finished server process [34452]
INFO 2022-05-23 16:32:57 Started server process [34519]
INFO 2022-05-23 16:32:57 Waiting for application startup.
INFO 2022-05-23 16:32:57 Application startup complete.
WARNING 2022-05-23 16:33:58 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:33:58 Shutting down
INFO 2022-05-23 16:33:58 Waiting for application shutdown.
INFO 2022-05-23 16:33:58 Application shutdown complete.
INFO 2022-05-23 16:33:58 Finished server process [34519]
INFO 2022-05-23 16:33:59 Started server process [34592]
INFO 2022-05-23 16:33:59 Waiting for application startup.
INFO 2022-05-23 16:33:59 Application startup complete.
WARNING 2022-05-23 16:40:17 StatReload detected file change in 'db/cache.py'. Reloading...
INFO 2022-05-23 16:40:17 Shutting down
INFO 2022-05-23 16:40:17 Waiting for application shutdown.
INFO 2022-05-23 16:40:17 Application shutdown complete.
INFO 2022-05-23 16:40:17 Finished server process [34592]
INFO 2022-05-23 16:42:54 Stopping reloader process [34282]
INFO 2022-05-23 16:42:57 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 16:42:57 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 16:42:57 Started reloader process [34817] using statreload
INFO 2022-05-23 16:42:58 Started server process [34819]
INFO 2022-05-23 16:42:58 Waiting for application startup.
INFO 2022-05-23 16:42:58 Application startup complete.
WARNING 2022-05-23 16:49:49 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:49:49 Shutting down
INFO 2022-05-23 16:49:49 Waiting for application shutdown.
INFO 2022-05-23 16:49:49 Application shutdown complete.
INFO 2022-05-23 16:49:49 Finished server process [34819]
INFO 2022-05-23 16:49:50 Started server process [34977]
INFO 2022-05-23 16:49:50 Waiting for application startup.
INFO 2022-05-23 16:49:50 Application startup complete.
WARNING 2022-05-23 16:50:49 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:50:49 Shutting down
INFO 2022-05-23 16:50:49 Waiting for application shutdown.
INFO 2022-05-23 16:50:49 Application shutdown complete.
INFO 2022-05-23 16:50:49 Finished server process [34977]
INFO 2022-05-23 16:50:50 Started server process [35021]
INFO 2022-05-23 16:50:50 Waiting for application startup.
INFO 2022-05-23 16:50:50 Application startup complete.
WARNING 2022-05-23 16:56:10 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 16:56:10 Shutting down
INFO 2022-05-23 16:56:10 Waiting for application shutdown.
INFO 2022-05-23 16:56:10 Application shutdown complete.
INFO 2022-05-23 16:56:10 Finished server process [35021]
INFO 2022-05-23 16:56:11 Started server process [35199]
INFO 2022-05-23 16:56:11 Waiting for application startup.
INFO 2022-05-23 16:56:11 Application startup complete.
WARNING 2022-05-23 17:01:27 StatReload detected file change in 'common/exceptions.py'. Reloading...
INFO 2022-05-23 17:01:27 Shutting down
INFO 2022-05-23 17:01:27 Waiting for application shutdown.
INFO 2022-05-23 17:01:27 Application shutdown complete.
INFO 2022-05-23 17:01:27 Finished server process [35199]
INFO 2022-05-23 17:01:28 Started server process [35299]
INFO 2022-05-23 17:01:28 Waiting for application startup.
INFO 2022-05-23 17:01:28 Application startup complete.
WARNING 2022-05-23 17:06:47 StatReload detected file change in 'common/resp.py'. Reloading...
INFO 2022-05-23 17:06:47 Shutting down
INFO 2022-05-23 17:06:47 Waiting for application shutdown.
INFO 2022-05-23 17:06:47 Application shutdown complete.
INFO 2022-05-23 17:06:47 Finished server process [35299]
INFO 2022-05-23 17:06:48 Started server process [35434]
INFO 2022-05-23 17:06:48 Waiting for application startup.
INFO 2022-05-23 17:06:48 Application startup complete.
WARNING 2022-05-23 17:11:03 StatReload detected file change in 'common/resp.py'. Reloading...
INFO 2022-05-23 17:11:04 Shutting down
INFO 2022-05-23 17:11:04 Waiting for application shutdown.
INFO 2022-05-23 17:11:04 Application shutdown complete.
INFO 2022-05-23 17:11:04 Finished server process [35434]
INFO 2022-05-23 17:11:05 Started server process [35667]
INFO 2022-05-23 17:11:05 Waiting for application startup.
INFO 2022-05-23 17:11:05 Application startup complete.
WARNING 2022-05-23 17:23:43 StatReload detected file change in 'apps/system/views.py'. Reloading...
INFO 2022-05-23 17:23:43 Shutting down
INFO 2022-05-23 17:23:43 Waiting for application shutdown.
INFO 2022-05-23 17:23:43 Application shutdown complete.
INFO 2022-05-23 17:23:43 Finished server process [35667]
INFO 2022-05-23 17:23:44 Started server process [36175]
INFO 2022-05-23 17:23:44 Waiting for application startup.
INFO 2022-05-23 17:23:44 Application startup complete.
INFO 2022-05-23 17:25:58 
ERROR 2022-05-23 17:25:58 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3459, in _do_configure_registries
    mapper._post_configure_properties()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1913, in _post_configure_properties
    prop.init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2141, in do_init
    self._process_dependent_arguments()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2236, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2103, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Users->users, expression 'User_Role' failed to locate a name ('User_Role'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.Users'> class after both dependent classes have been defined.
WARNING 2022-05-23 17:30:11 StatReload detected file change in 'apps/permission/models/role.py'. Reloading...
INFO 2022-05-23 17:30:11 Shutting down
INFO 2022-05-23 17:30:11 Waiting for application shutdown.
INFO 2022-05-23 17:30:11 Application shutdown complete.
INFO 2022-05-23 17:30:11 Finished server process [36175]
INFO 2022-05-23 17:30:12 Started server process [36286]
INFO 2022-05-23 17:30:12 Waiting for application startup.
INFO 2022-05-23 17:30:12 Application startup complete.
INFO 2022-05-23 17:30:16 
ERROR 2022-05-23 17:30:16 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3459, in _do_configure_registries
    mapper._post_configure_properties()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1913, in _post_configure_properties
    prop.init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2141, in do_init
    self._process_dependent_arguments()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2236, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2103, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Users->users, expression 'User_Role' failed to locate a name ('User_Role'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.Users'> class after both dependent classes have been defined.
WARNING 2022-05-23 17:30:28 StatReload detected file change in 'apps/permission/models/user.py'. Reloading...
INFO 2022-05-23 17:30:29 Shutting down
INFO 2022-05-23 17:30:29 Waiting for application shutdown.
INFO 2022-05-23 17:30:29 Application shutdown complete.
INFO 2022-05-23 17:30:29 Finished server process [36286]
INFO 2022-05-23 17:30:29 Started server process [36301]
INFO 2022-05-23 17:30:29 Waiting for application startup.
INFO 2022-05-23 17:30:29 Application startup complete.
INFO 2022-05-23 17:30:31 
ERROR 2022-05-23 17:30:31 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3459, in _do_configure_registries
    mapper._post_configure_properties()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1913, in _post_configure_properties
    prop.init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2141, in do_init
    self._process_dependent_arguments()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2236, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2103, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class UserRole->user_role, expression 'Role' failed to locate a name ('Role'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.UserRole'> class after both dependent classes have been defined.
INFO 2022-05-23 17:30:31 
ERROR 2022-05-23 17:30:31 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3455, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class UserRole->user_role'. Original exception was: When initializing mapper mapped class UserRole->user_role, expression 'Role' failed to locate a name ('Role'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.UserRole'> class after both dependent classes have been defined.
WARNING 2022-05-23 17:33:21 StatReload detected file change in 'apps/permission/models/user.py'. Reloading...
INFO 2022-05-23 17:33:21 Shutting down
INFO 2022-05-23 17:33:21 Waiting for application shutdown.
INFO 2022-05-23 17:33:21 Application shutdown complete.
INFO 2022-05-23 17:33:21 Finished server process [36301]
INFO 2022-05-23 17:33:22 Started server process [36365]
INFO 2022-05-23 17:33:22 Waiting for application startup.
INFO 2022-05-23 17:33:22 Application startup complete.
WARNING 2022-05-23 17:33:32 StatReload detected file change in 'apps/permission/models/user.py'. Reloading...
INFO 2022-05-23 17:33:32 Shutting down
INFO 2022-05-23 17:33:32 Waiting for application shutdown.
INFO 2022-05-23 17:33:32 Application shutdown complete.
INFO 2022-05-23 17:33:32 Finished server process [36365]
INFO 2022-05-23 17:33:33 Started server process [36376]
INFO 2022-05-23 17:33:33 Waiting for application startup.
INFO 2022-05-23 17:33:33 Application startup complete.
INFO 2022-05-23 17:33:33 
ERROR 2022-05-23 17:33:33 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3459, in _do_configure_registries
    mapper._post_configure_properties()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1913, in _post_configure_properties
    prop.init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2146, in do_init
    self._generate_backref()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2426, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'user' on relationship 'Users.user_role': property of that name exists on mapper 'mapped class UserRole->user_role'
WARNING 2022-05-23 17:33:45 StatReload detected file change in 'apps/permission/models/user.py'. Reloading...
INFO 2022-05-23 17:33:45 Shutting down
INFO 2022-05-23 17:33:45 Waiting for application shutdown.
INFO 2022-05-23 17:33:45 Application shutdown complete.
INFO 2022-05-23 17:33:45 Finished server process [36376]
INFO 2022-05-23 17:33:46 Started server process [36382]
INFO 2022-05-23 17:33:46 Waiting for application startup.
INFO 2022-05-23 17:33:46 Application startup complete.
INFO 2022-05-23 17:33:51 
ERROR 2022-05-23 17:33:51 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3459, in _do_configure_registries
    mapper._post_configure_properties()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1913, in _post_configure_properties
    prop.init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2141, in do_init
    self._process_dependent_arguments()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2236, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2103, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class UserRole->user_role, expression 'Roles' failed to locate a name ('Roles'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.UserRole'> class after both dependent classes have been defined.
INFO 2022-05-23 17:33:51 
ERROR 2022-05-23 17:33:51 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3455, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class UserRole->user_role'. Original exception was: When initializing mapper mapped class UserRole->user_role, expression 'Roles' failed to locate a name ('Roles'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.UserRole'> class after both dependent classes have been defined.
WARNING 2022-05-23 17:35:42 StatReload detected file change in 'apps/permission/models/user.py'. Reloading...
INFO 2022-05-23 17:35:42 Shutting down
INFO 2022-05-23 17:35:42 Waiting for application shutdown.
INFO 2022-05-23 17:35:42 Application shutdown complete.
INFO 2022-05-23 17:35:42 Finished server process [36382]
INFO 2022-05-23 17:35:43 Started server process [36433]
INFO 2022-05-23 17:35:43 Waiting for application startup.
INFO 2022-05-23 17:35:43 Application startup complete.
INFO 2022-05-23 17:35:45 
ERROR 2022-05-23 17:35:45 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 32, in getConfigSettingByID
    return respSuccessJson(config_setting_obj)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 17, in respSuccessJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ConfigSettings is not JSON serializable
INFO 2022-05-23 17:36:34 Shutting down
INFO 2022-05-23 17:36:34 Waiting for application shutdown.
INFO 2022-05-23 17:36:34 Application shutdown complete.
INFO 2022-05-23 17:36:34 Finished server process [36433]
INFO 2022-05-23 17:36:34 Stopping reloader process [34817]
INFO 2022-05-23 17:36:35 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 17:36:35 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 17:36:35 Started reloader process [36471] using statreload
INFO 2022-05-23 17:36:35 Started server process [36475]
INFO 2022-05-23 17:36:35 Waiting for application startup.
INFO 2022-05-23 17:36:35 Application startup complete.
INFO 2022-05-23 17:36:38 
ERROR 2022-05-23 17:36:38 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 31, in getConfigSettingByID
    config_setting_obj = curd_config_setting.get(db, id=id)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/curd_base.py", line 22, in get
    return db.query(self.model).filter(self.model.id == id, self.model.is_delete == 0).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2143, in query
    return self._query_cls(entities, self, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2119, in _post_inspect
    self._check_configure()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1896, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3459, in _do_configure_registries
    mapper._post_configure_properties()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1913, in _post_configure_properties
    prop.init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2141, in do_init
    self._process_dependent_arguments()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2236, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2103, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class UserRole->user_role, expression 'role.Roles' failed to locate a name ('role.Roles'). If this is a class name, consider adding this relationship() to the <class 'apps.permission.models.user.UserRole'> class after both dependent classes have been defined.
WARNING 2022-05-23 17:36:45 StatReload detected file change in 'apps/permission/models/user.py'. Reloading...
INFO 2022-05-23 17:36:45 Shutting down
INFO 2022-05-23 17:36:45 Waiting for application shutdown.
INFO 2022-05-23 17:36:45 Application shutdown complete.
INFO 2022-05-23 17:36:45 Finished server process [36475]
INFO 2022-05-23 17:36:46 Started server process [36480]
INFO 2022-05-23 17:36:46 Waiting for application startup.
INFO 2022-05-23 17:36:46 Application startup complete.
INFO 2022-05-23 17:38:30 Shutting down
INFO 2022-05-23 17:38:30 Waiting for application shutdown.
INFO 2022-05-23 17:38:30 Application shutdown complete.
INFO 2022-05-23 17:38:30 Finished server process [36480]
INFO 2022-05-23 17:38:30 Stopping reloader process [36471]
INFO 2022-05-23 17:38:31 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 17:38:31 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 17:38:31 Started reloader process [36530] using statreload
INFO 2022-05-23 17:38:32 Started server process [36532]
INFO 2022-05-23 17:38:32 Waiting for application startup.
INFO 2022-05-23 17:38:32 Application startup complete.
INFO 2022-05-23 17:39:15 
ERROR 2022-05-23 17:39:15 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 32, in getConfigSettingByID
    return respSuccessJson(config_setting_obj)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 17, in respSuccessJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ConfigSettings is not JSON serializable
WARNING 2022-05-23 17:44:20 StatReload detected file change in 'apps/system/views.py'. Reloading...
INFO 2022-05-23 17:44:21 Shutting down
INFO 2022-05-23 17:44:21 Waiting for application shutdown.
INFO 2022-05-23 17:44:21 Application shutdown complete.
INFO 2022-05-23 17:44:21 Finished server process [36532]
INFO 2022-05-23 17:44:22 Started server process [36732]
INFO 2022-05-23 17:44:22 Waiting for application startup.
INFO 2022-05-23 17:44:22 Application startup complete.
INFO 2022-05-23 17:44:23 
INFO 2022-05-23 17:44:23 <apps.system.models.config_settings.ConfigSettings object at 0x12ad53b20>
ERROR 2022-05-23 17:44:23 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 33, in getConfigSettingByID
    return respSuccessJson(config_setting_obj)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 17, in respSuccessJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ConfigSettings is not JSON serializable
WARNING 2022-05-23 17:49:00 StatReload detected file change in 'apps/system/views.py'. Reloading...
INFO 2022-05-23 17:49:00 Shutting down
INFO 2022-05-23 17:49:00 Waiting for application shutdown.
INFO 2022-05-23 17:49:00 Application shutdown complete.
INFO 2022-05-23 17:49:00 Finished server process [36732]
INFO 2022-05-23 17:49:01 Started server process [36830]
INFO 2022-05-23 17:49:01 Waiting for application startup.
INFO 2022-05-23 17:49:01 Application startup complete.
INFO 2022-05-23 17:49:13 
INFO 2022-05-23 17:49:13 <apps.system.models.config_settings.ConfigSettings object at 0x133b53b20>
ERROR 2022-05-23 17:49:13 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 33, in getConfigSettingByID
    return respSuccessJson(config_setting_obj.dict())
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 17, in respSuccessJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
WARNING 2022-05-23 17:56:43 StatReload detected file change in 'common/curd_base.py'. Reloading...
INFO 2022-05-23 17:56:43 Shutting down
INFO 2022-05-23 17:56:43 Waiting for application shutdown.
INFO 2022-05-23 17:56:43 Application shutdown complete.
INFO 2022-05-23 17:56:43 Finished server process [36830]
WARNING 2022-05-23 18:03:47 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
WARNING 2022-05-23 18:04:37 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 18:04:37 Started server process [37292]
INFO 2022-05-23 18:04:37 Waiting for application startup.
INFO 2022-05-23 18:04:37 Application startup complete.
WARNING 2022-05-23 18:09:07 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 18:09:07 Shutting down
INFO 2022-05-23 18:09:07 Waiting for application shutdown.
INFO 2022-05-23 18:09:07 Application shutdown complete.
INFO 2022-05-23 18:09:07 Finished server process [37292]
WARNING 2022-05-23 18:11:28 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
WARNING 2022-05-23 18:15:46 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 18:15:47 Started server process [37540]
INFO 2022-05-23 18:15:47 Waiting for application startup.
INFO 2022-05-23 18:15:47 Application startup complete.
WARNING 2022-05-23 18:19:43 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 18:19:43 Shutting down
INFO 2022-05-23 18:19:43 Waiting for application shutdown.
INFO 2022-05-23 18:19:43 Application shutdown complete.
INFO 2022-05-23 18:19:43 Finished server process [37540]
WARNING 2022-05-23 18:21:01 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 18:21:02 Started server process [37723]
INFO 2022-05-23 18:21:02 Waiting for application startup.
INFO 2022-05-23 18:21:02 Application startup complete.
WARNING 2022-05-23 18:31:46 StatReload detected file change in 'apps/system/views.py'. Reloading...
INFO 2022-05-23 18:31:46 Shutting down
INFO 2022-05-23 18:31:46 Waiting for application shutdown.
INFO 2022-05-23 18:31:46 Application shutdown complete.
INFO 2022-05-23 18:31:46 Finished server process [37723]
INFO 2022-05-23 18:31:47 Started server process [38032]
INFO 2022-05-23 18:31:47 Waiting for application startup.
INFO 2022-05-23 18:31:47 Application startup complete.
INFO 2022-05-23 18:31:47 
INFO 2022-05-23 18:31:47 {'id': 1, 'create_time': '2022-05-21 02:43:05', 'status': 0, 'key': 'key1', 'name': 'name1', 'value': '1', 'typeof': '', 'remark': ''}
WARNING 2022-05-23 18:33:39 StatReload detected file change in 'apps/system/views.py'. Reloading...
INFO 2022-05-23 18:33:39 Shutting down
INFO 2022-05-23 18:33:40 Waiting for application shutdown.
INFO 2022-05-23 18:33:40 Application shutdown complete.
INFO 2022-05-23 18:33:40 Finished server process [38032]
INFO 2022-05-23 18:33:40 Started server process [38158]
INFO 2022-05-23 18:33:40 Waiting for application startup.
INFO 2022-05-23 18:33:40 Application startup complete.
INFO 2022-05-23 18:35:45 
ERROR 2022-05-23 18:35:45 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 26, in getConfigSettingByKey
    config_setting_obj = curd_config_setting.getByKey(db, key=key)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/curd/crud_config_setting.py", line 20, in getByKey
    self.model.status._in((0,))).first()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 329, in __getattr__
    util.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with ConfigSettings.status has an attribute '_in'
WARNING 2022-05-23 18:36:39 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 18:36:39 Shutting down
INFO 2022-05-23 18:36:39 Waiting for application shutdown.
INFO 2022-05-23 18:36:39 Application shutdown complete.
INFO 2022-05-23 18:36:39 Finished server process [38158]
INFO 2022-05-23 18:36:40 Started server process [38195]
INFO 2022-05-23 18:36:40 Waiting for application startup.
INFO 2022-05-23 18:36:40 Application startup complete.
INFO 2022-05-23 18:36:45 
INFO 2022-05-23 18:36:45 {'key': 'key1', 'name': 'name1', 'value': 1, 'value_str': '1'}
INFO 2022-05-23 19:15:45 Shutting down
INFO 2022-05-23 19:15:46 Waiting for application shutdown.
INFO 2022-05-23 19:15:46 Application shutdown complete.
INFO 2022-05-23 19:15:46 Finished server process [38195]
INFO 2022-05-23 19:15:46 Stopping reloader process [36530]
INFO 2022-05-23 19:15:47 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 19:15:47 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 19:15:47 Started reloader process [38952] using statreload
INFO 2022-05-23 19:15:47 Started server process [38956]
INFO 2022-05-23 19:15:47 Waiting for application startup.
INFO 2022-05-23 19:15:47 Application startup complete.
INFO 2022-05-23 19:17:30 
INFO 2022-05-23 19:17:30 {'key': 'key1', 'name': 'name1', 'value': 1, 'value_str': '1'}
INFO 2022-05-23 19:17:49 
INFO 2022-05-23 19:17:49 {'id': 1, 'create_time': '2022-05-21 02:43:05', 'status': 0, 'key': 'key1', 'name': 'name1', 'value': '1', 'typeof': '', 'remark': ''}
INFO 2022-05-23 19:18:34 Shutting down
INFO 2022-05-23 19:18:34 Waiting for application shutdown.
INFO 2022-05-23 19:18:34 Application shutdown complete.
INFO 2022-05-23 19:18:34 Finished server process [38956]
INFO 2022-05-23 19:18:34 Stopping reloader process [38952]
INFO 2022-05-23 19:18:35 Will watch for changes in these directories: ['/Users/beginner/Projects/temp/fastapi-vue/backend/app']
INFO 2022-05-23 19:18:35 Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO 2022-05-23 19:18:35 Started reloader process [39026] using statreload
INFO 2022-05-23 19:18:35 Started server process [39028]
INFO 2022-05-23 19:18:35 Waiting for application startup.
INFO 2022-05-23 19:18:35 Application startup complete.
INFO 2022-05-23 19:19:23 
WARNING 2022-05-23 19:21:10 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 19:21:10 Shutting down
INFO 2022-05-23 19:21:10 Waiting for application shutdown.
INFO 2022-05-23 19:21:10 Application shutdown complete.
INFO 2022-05-23 19:21:10 Finished server process [39028]
INFO 2022-05-23 19:21:11 Started server process [39089]
INFO 2022-05-23 19:21:11 Waiting for application startup.
INFO 2022-05-23 19:21:11 Application startup complete.
INFO 2022-05-23 19:21:25 
INFO 2022-05-23 19:21:52 
INFO 2022-05-23 19:21:52 {'id': 1, 'create_time': datetime.datetime(2022, 5, 23, 19, 19, 24), 'status': 0, 'key': 'key1', 'name': 'name1', 'value': '1', 'typeof': 'int', 'remark': ''}
ERROR 2022-05-23 19:21:52 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 39, in getConfigSettingByID
    return respSuccessJson(config_setting_obj)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 17, in respSuccessJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
WARNING 2022-05-23 19:32:07 StatReload detected file change in 'apps/system/curd/crud_config_setting.py'. Reloading...
INFO 2022-05-23 19:32:07 Shutting down
INFO 2022-05-23 19:32:07 Waiting for application shutdown.
INFO 2022-05-23 19:32:07 Application shutdown complete.
INFO 2022-05-23 19:32:07 Finished server process [39089]
INFO 2022-05-23 19:32:08 Started server process [39324]
INFO 2022-05-23 19:32:08 Waiting for application startup.
INFO 2022-05-23 19:32:08 Application startup complete.
INFO 2022-05-23 19:32:16 
INFO 2022-05-23 19:32:16 <class 'datetime.datetime'>
INFO 2022-05-23 19:32:16 {'id': 1, 'create_time': datetime.datetime(2022, 5, 23, 19, 19, 24), 'status': 0, 'key': 'key1', 'name': 'name1', 'value': '1', 'typeof': 'int', 'remark': ''}
ERROR 2022-05-23 19:32:16 Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/apps/system/views.py", line 39, in getConfigSettingByID
    return respSuccessJson(config_setting_obj)
  File "/Users/beginner/Projects/temp/fastapi-vue/backend/app/common/resp.py", line 17, in respSuccessJson
    return JSONResponse(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/responses.py", line 178, in render
    return json.dumps(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
INFO 2022-05-24 19:27:45 Shutting down
INFO 2022-05-24 19:27:45 Waiting for application shutdown.
INFO 2022-05-24 19:27:45 Application shutdown complete.
INFO 2022-05-24 19:27:45 Finished server process [39324]
